// FUNCTIONID TEHTE POHISED
// +-*/ ONCLICK TAKE FIRST VALUE FROM DIV INNERHTML
// ADD +-*/ TO CALCULATOR SCREEN
// USER ENTERS SECOND VALUE
// UPON ANS OR NEW +-*/ CLICK ADD ANSWER TO ANSWER ROW ON CALCULATOR
// CLEAR CALCULATION ROW

// FURHTER USE CLEAR ANSWER ROW
// IF PRESS ANS USE PREVIOUS ANSWER FOR NEW CALCULATION
// ELSE ADD NEW NUMBER INPUT TO CALCULATION ROW